services:
  auth_postgres:
    image: postgres:15
    container_name: fidicus-auth-db
    restart: always
    environment:
      POSTGRES_DB:       ${AUTH_PGSQL}
      POSTGRES_USER:     ${AUTH_PGSQL_USER}
      POSTGRES_PASSWORD: ${AUTH_PGSQL_PASSW}
    ports:
      - "${AUTH_PGSQL_PORT}:5432"
    volumes:
      - fid_auth_pgsql:/var/lib/postgresql/data

  schema_postgres:
    image: postgres:15
    container_name: fidicus-schema-pgsql
    restart: always
    environment:
      POSTGRES_DB:      ${SCHEMA_PGSQL}
      POSTGRES_USER:    ${SCHEMA_PGSQL_USER}
      POSTGRES_PASSWORD: ${SCHEMA_PGSQL_PASSW}
    ports:
      - "${SCHEMA_PGSQL_PORT}:5432"
    volumes:
      - fid_schema_pgsql:/var/lib/postgresql/data

  schema_neo4j:
    image: neo4j:5.26.0
    container_name: fidicus-neo4j
    restart: always
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7474:7474"  ## HTTP Access
      - "7687:7687"  ## Bolt protocol for Drivers
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/var/lib/neo4j/conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http:localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  fid_auth_pgsql:
  fid_schema_pgsql:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
